CREATE TABLE IF NOT EXISTS DEVICES
(
    ID            INTEGER PRIMARY KEY AUTOINCREMENT,
    DEVICE_NAME   TEXT NOT NULL,
    SERIAL_NUMBER TEXT NOT NULL UNIQUE,
    MANUFACTURER  TEXT NULL,
    MODEL         TEXT NULL,
    DEVICE_TYPE   TEXT NULL,
    LAST_SEEN     TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS DEVICE_OWNER
(
    ID              INTEGER PRIMARY KEY AUTOINCREMENT,
    SERIAL_NUMBER       TEXT     NOT NULL,
    IMMICH_USER_ID  VARCHAR(36) NOT NULL,
    UNIQUE(SERIAL_NUMBER, IMMICH_USER_ID)
);

CREATE TABLE IF NOT EXISTS IMPORT_JOB_OWNER
(
    ID              INTEGER PRIMARY KEY AUTOINCREMENT,
    IMPORT_JOB      VARCHAR(36) NOT NULL UNIQUE, -- UUID for jobben
    IMMICH_USER_ID  VARCHAR(36) NOT NULL,
    LOCKED          BOOLEAN DEFAULT 0
);

CREATE TABLE IF NOT EXISTS IMPORTED_FILES
(
    ID            INTEGER PRIMARY KEY AUTOINCREMENT,
    IMPORT_JOB    VARCHAR(36) NOT NULL,
    DEVICE_ID     INTEGER     NOT NULL,
    FILE_NAME     TEXT        NOT NULL,
    FILE_SIZE     INTEGER     NOT NULL,
    FILE_TYPE     VARCHAR(50) NOT NULL, -- 'IMAGE' eller 'VIDEO'
    EXTENSION     TEXT        NOT NULL, -- f.eks. 'jpg', 'mp4'
    CHECKSUM      VARCHAR(50) NOT NULL,
    CHECKSUM_TYPE VARCHAR(12) NOT NULL,
    IMPORTED_AT   TEXT        NOT NULL,
    FOREIGN KEY (DEVICE_ID) REFERENCES DEVICES (ID) ON DELETE CASCADE
);


CREATE TABLE IF NOT EXISTS IMMICH_USERS
(
    ID         INTEGER PRIMARY KEY AUTOINCREMENT,
    USER_ID    VARCHAR(36)  NOT NULL UNIQUE,
    NAME       VARCHAR(255) NOT NULL,
    EMAIL      VARCHAR(255) NOT NULL,
    CREATED_AT VARCHAR(50)  NOT NULL,
    IS_ACTIVE  BOOLEAN      NOT NULL DEFAULT 0,
    DATA       TEXT         NOT NULL
);

CREATE TABLE IF NOT EXISTS IMMICH_API_KEY
(
    ID         INTEGER PRIMARY KEY AUTOINCREMENT,
    USER_ID    VARCHAR(36)  NOT NULL,
    API_KEY_ID VARCHAR(36)  NOT NULL,
    SERVER_URL VARCHAR(512) NOT NULL,
    API_KEY    VARCHAR(255) NOT NULL,
    CREATED_AT VARCHAR(50)  NOT NULL,
    IS_ACTIVE  BOOLEAN      NOT NULL DEFAULT 0,
    DATA       TEXT         NOT NULL,
    CONSTRAINT fk_user
        FOREIGN KEY (USER_ID)
            REFERENCES IMMICH_USERS (USER_ID)
            ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS ALBUMS
(
    ID             INTEGER PRIMARY KEY AUTOINCREMENT,
    IMMICH_USER_ID VARCHAR(36) NOT NULL,
    TITLE          TEXT        NOT NULL,
    DESCRIPTION    TEXT,
    START_DATE     TEXT,
    END_DATE       TEXT,
    USE            BOOLEAN,
    CREATED_AT     TEXT        NOT NULL,
    IMMICH_ALBUM_ID VARCHAR(36) DEFAULT NULL,
    FOREIGN KEY (IMMICH_USER_ID) REFERENCES IMMICH_USERS (USER_ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS UPLOAD_FILES
(
    ID               INTEGER PRIMARY KEY AUTOINCREMENT,
    IMMICH_USER_ID   VARCHAR(36) NOT NULL,
    IMPORTED_FILE_ID INTEGER     NOT NULL,
    ALBUM_ID         INTEGER,
    STATE            TEXT        NOT NULL DEFAULT 'NOT_READY', -- NOT_READY, READY, IN_QUEUE, UPLOADED, FAILED
    RETRY_COUNT      INTEGER     NOT NULL DEFAULT 0,
    ERROR_MESSAGE    TEXT,
    UPDATED_AT       TEXT        NOT NULL,
    FOREIGN KEY (IMPORTED_FILE_ID) REFERENCES IMPORTED_FILES (ID) ON DELETE CASCADE,
    FOREIGN KEY (ALBUM_ID) REFERENCES ALBUMS (ID) ON DELETE SET NULL
);


CREATE INDEX idx_file_lookup ON IMPORTED_FILES (DEVICE_ID, FILE_NAME, FILE_SIZE);