CREATE TABLE IF NOT EXISTS DEVICES
(
    ID            INTEGER PRIMARY KEY AUTOINCREMENT,
    DEVICE_NAME   TEXT NOT NULL,
    SERIAL_NUMBER TEXT NOT NULL UNIQUE,
    FRIENDLY_NAME TEXT NULL,
    MANUFACTURER  TEXT NULL,
    MODEL         TEXT NULL,
    LAST_SEEN     TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS IMPORTED_FILES
(
    ID          INTEGER PRIMARY KEY AUTOINCREMENT,
    DEVICE_ID   INTEGER     NOT NULL,
    FILE_NAME   TEXT        NOT NULL,
    FILE_SIZE   INTEGER     NOT NULL,
    FILE_TYPE   VARCHAR(50) NOT NULL, -- 'IMAGE' eller 'VIDEO'
    EXTENSION   TEXT        NOT NULL, -- f.eks. 'jpg', 'mp4'
    IMPORTED_AT TEXT        NOT NULL,
    FOREIGN KEY (DEVICE_ID) REFERENCES DEVICES (ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS IMPORT_OPERATIONS
(
    ID              INTEGER PRIMARY KEY AUTOINCREMENT,
    DEVICE_ID       INTEGER NOT NULL,
    NEW_FILES_COUNT INTEGER NOT NULL,
    RAN_AT          TEXT    NOT NULL,
    FOREIGN KEY (DEVICE_ID) REFERENCES DEVICES (ID) ON DELETE CASCADE
);

CREATE INDEX idx_file_lookup ON IMPORTED_FILES (DEVICE_ID, FILE_NAME, FILE_SIZE);