CREATE TABLE IF NOT EXISTS DELETE_FILES
(
    ID                  INTEGER PRIMARY KEY AUTOINCREMENT,

    IMPORTED_FILE_ID    INTEGER NOT NULL UNIQUE,
    UPLOAD_FILE_ID      INTEGER NOT NULL UNIQUE,

    CAMERA_STATE        TEXT NOT NULL DEFAULT 'PENDING',
    CAMERA_DELETED_AT   TEXT NULL,
    CAMERA_ERROR_MESSAGE TEXT NULL,

    LOCAL_STATE         TEXT NOT NULL DEFAULT 'PENDING',
    LOCAL_DELETED_AT    TEXT NULL,
    LOCAL_ERROR_MESSAGE TEXT NULL,

    RETRY_COUNT         INTEGER NOT NULL DEFAULT 0,

    CREATED_AT          TEXT NOT NULL,
    UPDATED_AT          TEXT NOT NULL,

    FOREIGN KEY (IMPORTED_FILE_ID)
        REFERENCES IMPORTED_FILES (ID)
        ON DELETE CASCADE,

    FOREIGN KEY (UPLOAD_FILE_ID)
        REFERENCES UPLOAD_FILES (ID)
        ON DELETE CASCADE
);