CREATE TABLE IF NOT EXISTS IMMICH_USERS
(
    ID         INTEGER PRIMARY KEY AUTOINCREMENT,
    USER_ID    VARCHAR(36) NOT NULL UNIQUE,
    NAME       VARCHAR(255) NOT NULL,
    EMAIL      VARCHAR(255) NOT NULL,
    CREATED_AT VARCHAR(50) NOT NULL,
    IS_ACTIVE  BOOLEAN NOT NULL DEFAULT 0,
    DATA       TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS IMMICH_API_KEY
(
    ID         INTEGER PRIMARY KEY AUTOINCREMENT,
    USER_ID    VARCHAR(36) NOT NULL,
    API_KEY_ID    VARCHAR(36) NOT NULL,
    SERVER_URL VARCHAR(512) NOT NULL,
    API_KEY    VARCHAR(255) NOT NULL,
    CREATED_AT VARCHAR(50) NOT NULL,
    IS_ACTIVE  BOOLEAN NOT NULL DEFAULT 0,
    DATA       TEXT NOT NULL,
    CONSTRAINT fk_user
        FOREIGN KEY (USER_ID)
            REFERENCES IMMICH_USERS(USER_ID)
            ON DELETE CASCADE
);