spring:
  application:
    name: Kammich

  flyway:
    enabled: true
    locations: classpath:flyway
    # 'baseline-on-migrate' er bra for å unngå feil ved første oppstart på tom db
    baseline-on-migrate: true

# Valgfritt: Hvis du vil at loggene skal være mer lesbare
logging:
  level:
    # Sett din egen tjeneste til DEBUG for å se log.info/debug-meldingene dine
    no.iktdev.kammich: DEBUG

    # Valgfritt: Hvis du vil se hva Spring/GPhoto2 driver med internt
    org.springframework: INFO
    org.flywaydb: INFO
    no.iktdev.kammich.services.importing.DeviceContentIndexing: OFF
    no.iktdev.kammich.gphoto2.parsers.GPhoto2FileListParser: OFF
    no.iktdev.kammich.storage.DeviceManagerService: OFF
    no.iktdev.kammich.ConfigService: INFO
